services:
  Autobus\Bundle\BusBundle\Security\SecurityChain: ~

  Autobus\Bundle\BusBundle\Security\Strategy\BasicAuthStrategy:
    tags: ['bus.security_strategy']

  Autobus\Bundle\BusBundle\Security\Strategy\IPWhiteListStrategy:
    tags: ['bus.security_strategy']
