services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Controllers
  Autobus\Bundle\BusBundle\Controller\:
    resource: '../../Controller'

  # Services
  Autobus\Bundle\BusBundle\Runner\RunnerChain: ~

  Autobus\Bundle\BusBundle\Runner\RunnerCollection:
    arguments: [!tagged bus.runner]
    public: true

  Autobus\Bundle\BusBundle\Form\JobType:
    tags: ['form.type']

  Autobus\Bundle\BusBundle\Form\CronJobType:
    tags: ['bus.job_type']

  Autobus\Bundle\BusBundle\Form\QueueJobType:
    tags: ['bus.job_type']

  Autobus\Bundle\BusBundle\Form\TopicJobType:
    tags: ['bus.job_type']

  Autobus\Bundle\BusBundle\Form\WebJobType:
    tags: ['bus.job_type']

  Autobus\Bundle\BusBundle\Form\JobTypeCollection:
    arguments: [!tagged bus.job_type]
    public: true

  Autobus\Bundle\BusBundle\Entity\JobFactory: ~

  Autobus\Bundle\BusBundle\Form\JobTypeFactory:
    arguments:
    - '@Autobus\Bundle\BusBundle\Form\JobTypeCollection'

  Autobus\Bundle\BusBundle\EventListener\StartExecutionSubscriber:
    tags: ['kernel.event_subscriber']

  Autobus\Bundle\BusBundle\EventListener\FinishExecutionSubscriber:
    arguments:
      - '@mailer'
      - '@translator'
      - '%app.sender_email%'
      - '%app.sender_email_name%'
    tags: ['kernel.event_subscriber']

  Autobus\Bundle\BusBundle\EventListener\RunnerExceptionHandleSubscriber:
    tags: ['kernel.event_subscriber']

  Autobus\Bundle\BusBundle\EventListener\SecureWebJobSubscriber:
    arguments:
      - '@Autobus\Bundle\BusBundle\Security\SecurityChain'
    tags: ['kernel.event_subscriber']

  Autobus\Bundle\BusBundle\Converter\JobParamConverter:
    arguments:
      - '@Autobus\Bundle\BusBundle\Routing\Matcher\JobUrlMatcher'
      - '@doctrine.orm.entity_manager'
    tags:
      - { name: request.param_converter, converter: bus_job_converter}

  Symfony\Component\Routing\RouteCollection: ~

  Autobus\Bundle\BusBundle\Routing\Matcher\JobUrlMatcher:
    arguments:
      - '@Symfony\Component\Routing\RouteCollection'
      - '@router.request_context'

  # Queue
  Autobus\Bundle\BusBundle\Queue\PubSubWriter:
    tags: ['bus.queue_writer']

  Autobus\Bundle\BusBundle\Queue\SqsWriter:
    tags: ['bus.queue_writer']

  Autobus\Bundle\BusBundle\Queue\WriterCollection:
    arguments: [ !tagged bus.queue_writer ]
    public: true

  Autobus\Bundle\BusBundle\Queue\WriterFactory: ~

  # Helper
  Autobus\Bundle\BusBundle\Helper\JobHelper:
    arguments:
      - '@kernel'

  Autobus\Bundle\BusBundle\Helper\TopicHelper: ~

  Autobus\Bundle\BusBundle\Helper\SqsHelper: ~

  # Command
  Autobus\Bundle\BusBundle\Command\AutobusCronRunCommand:
    tags:
    - { name: console.command }

  Autobus\Bundle\BusBundle\Command\PubSubConsumeCommand:
    tags:
    - { name: console.command }

  Autobus\Bundle\BusBundle\Command\SqsConsumeCommand:
    tags:
      - { name: console.command }

  Autobus\Bundle\BusBundle\Command\ClearExecutionsCommand:
    tags:
      - { name: console.command }

