<?php

namespace Autobus\Bundle\BusBundle\Repository;

use Autobus\Bundle\BusBundle\Entity\CronJob;

/**
 * CronJobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CronJobRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get due jobs
     *
     * @param \DateTime $date
     *
     * @return CronJob[]
     */
    public function findDueJobs($date = null)
    {
        if (is_null($date)) {
            $date = new \DateTime();
        }

        $query = $this->createQueryBuilder('j')
          ->where('j.nextRunDate <= :date OR j.nextRunDate IS NULL')
          ->setParameter('date', $date->format('Y-m-d H:i:s'));

        return $query->getQuery()->getResult();
    }
}
