<?php

namespace Autobus\Bundle\BusBundle\Repository;

use Autobus\Bundle\BusBundle\Entity\Job;

/**
 * ExecutionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExecutionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get executions query by $job
     *
     * @param Job $job
     *
     * @return Execution[]
     */
    public function getQueryByJob(Job $job)
    {
        return $this->createQueryBuilder('e')
                    ->where('e.job = :jobId')
                    ->setParameters([
                        'jobId' => $job->getId(),
                    ])
                    ->getQuery();
    }
}
