<?php

namespace Autobus\Bundle\BusBundle\Repository;

use Autobus\Bundle\BusBundle\Entity\Job;

/**
 * ExecutionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExecutionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get executions query by $job
     *
     * @param Job    $job
     * @param string $dateSort
     *
     * @return Execution[]
     */
    public function getQueryByJob(Job $job, $dateSort = 'DESC')
    {
        return $this->createQueryBuilder('e')
                    ->where('e.job = :jobId')
                    ->setParameters([
                        'jobId' => $job->getId(),
                    ])
                    ->orderBy('e.date', $dateSort)
                    ->getQuery();
    }

    /**
     * Get executions created before $date
     *
     * @param \DateTime $date
     *
     * @return Execution[]
     */
    public function getBeforeDate(\DateTime $date)
    {
        return $this->createQueryBuilder('e')
                    ->where('e.date < :date')
                    ->setParameter('date', $date->format('Y-m-d H:i:s'))
                    ->getQuery()
                    ->getResult();
    }
}
