<?php

namespace Autobus\Bundle\BusBundle\Repository;

/**
 * JobGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
