<?php

namespace Autobus\Bundle\BusBundle\Repository;

use Autobus\Bundle\BusBundle\Entity\WebJob;

/**
 * WebJobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebJobRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $prefix
     *
     * @return WebJob[]
     */
    public function findAllMatchingPrefix($prefix)
    {
        $qb = $this->createQueryBuilder('w');
        $qb->where('w.path LIKE :prefix')
            ->setParameter('prefix', '%'.$prefix.'%');

        return $qb->getQuery()->execute();
    }
}
